# Generated by Django 3.2 on 2021-05-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('pearl', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
    ]
