# Generated by Django 3.2 on 2021-05-27 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 27, 7, 21, 3, 487803), verbose_name=datetime.datetime(2021, 5, 27, 7, 20, 39, 993431)),
            preserve_default=False,
        ),
    ]
