# Generated by Django 3.2 on 2022-02-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('FAITH', 'LOVE'), ('WISDOM', 'POWER')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
