# Generated by Django 3.2 on 2021-06-04 14:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0003_auto_20210604_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 4, 14, 9, 38, 968061, tzinfo=utc)),
        ),
    ]
