# Generated by Django 3.2 on 2022-02-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0003_auto_20220219_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='pearl_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='summary',
            new_name='pearl_scripture',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='pearl_summary',
        ),
    ]
