# Generated by Django 3.2 on 2021-06-07 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0004_alter_post_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 19, 23, 22, 38113, tzinfo=utc)),
        ),
    ]
