# Generated by Django 3.2 on 2022-04-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0005_alter_post_pearl_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='todays_date',
            field=models.DateTimeField(default='Tue Apr 12 23:02:30 2022'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pearl_category',
            field=models.CharField(choices=[('FOR FAITH', 'for faith'), ('FOR WISDOM', 'for wisdom'), ('FOR LOVE', 'for love'), ('FOR POWER', 'for power')], max_length=200),
        ),
    ]
