# Generated by Django 3.2 on 2022-04-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0006_auto_20220412_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='todays_date',
            field=models.TimeField(default='Tue Apr 12 23:18:51 2022'),
        ),
    ]
