# Generated by Django 3.2 on 2021-07-05 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0008_auto_20210703_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.date(2021, 7, 5)),
        ),
    ]
