# Generated by Django 3.2 on 2021-07-09 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0010_alter_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='pearl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pearl.post'),
        ),
    ]
