# Generated by Django 3.2 on 2021-07-10 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pearl', '0011_archive_pearl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='pearl',
            new_name='post',
        ),
    ]
