# Generated by Django 3.2 on 2021-07-10 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pearl', '0012_rename_pearl_archive_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='in_archive',
        ),
        migrations.AddField(
            model_name='post',
            name='archived',
            field=models.ManyToManyField(blank=True, related_name='archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
    ]
