# Generated by Django 3.2 on 2021-08-22 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pearl', '0013_auto_20210710_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='archived',
            field=models.ManyToManyField(blank=True, related_name='archived_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
